---
site_name: Community Labs
site_url: https://noredistribution.github.com/clabs
repo_name: Clabs
repo_url: https://github.com/noredistribution/clabs

extra_css:
  - assets/stylesheets/extra.css

theme:
  logo: assets/img/arista-logo.png
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tooltips
    - header.autohide
    - navigation.indexes
    - navigation.tabs
    - navigation.prune
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/gears
    annotation: material/plus-circle

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # allows list ident with 2 spaces
  - mdx_truly_sane_lists
  - md_in_html #Enable the use of captioned images via techniques shown here: https://squidfunk.github.io/mkdocs-material/reference/images/

extra:
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.


plugins:
  - privacy
  - search
  - glightbox

nav:
  - Home:
      - Clabs: index.md

